### PR TITLE
Update LSP4J artifact name eclipse/lsp4j#487

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by spoenemann** [comment]
I don't know whether this publishing workflow is still used for LSP4J. @jonahgraham can you help?

**Comment by cdietrich** [comment]
already asked here https://github.com/eclipse/lsp4j/pull/487#issuecomment-763400973

**Comment by jonahgraham** [comment]
> already asked here [eclipse/lsp4j#487 (comment)](https://github.com/eclipse/lsp4j/pull/487#issuecomment-763400973)

@spoenemann see reply there.

**Comment by spoenemann** [comment]
Ok we can change it anyway.

**Pull request merged**
