### PR TITLE
[#3][eclipse/xtext#1230] Added support for new download.checksum.md5 and download.checksum.sha-256 properties

### PR DESCRIPTION
**Pull request by cdietrich**
[#3][eclipse/xtext#1230] Added support for new download.checksum.md5 and download.checksum.sha-256 properties

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
@spoenemann @dhuebner please review

**Comment by cdietrich** [comment]
any hints how i can test this locally?

**Comment by cdietrich** [comment]
@svenefftinge anybody out there?

**Comment by svenefftinge** [comment]
Vacation time for Miro and Dennis.

**Comment by svenefftinge** [comment]
@meysholdt Could you check?

**Review by svenefftinge — APPROVED** [review]
LGTM

**Comment by meysholdt** [comment]
LGTM, too.

**Comment by cdietrich** [comment]
please note. i dont have rights to merge

**Pull request merged**
